
- hosts: sdlc
  tags:
    - hdfs

  vars:
    hs2_jdbc_url: jdbc:hive2://{{ zookeeper_server }}:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2
    hive_superuser: hive
    hive_superpassword: hive

  tasks:
    - name: Create User Home Directories on local filesystem
      file:
        path: /home/{{ item }}
        state: directory
        mode: 0750
        owner: '{{ item }}'
      become: true
      loop:
        - bammbamm
        - fred
        - wilma
        - barney
        - betty
        - pebbles
        - bedrock
        - arya
        - jonsnow
        - cersei
        - daenerys
        - sansa
        - tyrion
        - winterfell
        - kingslanding
        - anakin
        - hansolo
        - leia
        - luke
        - padme
        - yoda
        - coruscant
        - tatooine
      tags:
        - local
        - ldap
        - hdp

    - name: Create User Home Directories in hdfs
      shell: hdfs dfs -mkdir -p /user/{{ item }}/datasets/external;hdfs dfs -chown -R {{ item }}:hadoop /user/{{ item }}
      loop:
        - bammbamm
        - fred
        - wilma
        - barney
        - betty
        - pebbles
        - bedrock
        - arya
        - jonsnow
        - cersei
        - daenerys
        - sansa
        - tyrion
        - winterfell
        - kingslanding
        - anakin
        - hansolo
        - leia
        - luke
        - padme
        - yoda
        - coruscant
        - tatooine
      become: true
      become_user: hdfs
      tags:
        - hdp

    - name: Create Private User Database
      shell: /usr/hdp/current/hive-client/bin/beeline -u "{{ hs2_jdbc_url}}" -n {{ hive_superuser }} -p {{ hive_superpassword }} -e "create database if not exists priv_{{ item }} LOCATION '/user/{{ item }}/datasets/internal.db'"
      loop:
        - bammbamm
        - fred
        - wilma
        - barney
        - betty
        - pebbles
        - bedrock
        - arya
        - jonsnow
        - cersei
        - daenerys
        - sansa
        - tyrion
        - winterfell
        - kingslanding
        - anakin
        - hansolo
        - leia
        - luke
        - padme
        - yoda
        - coruscant
        - tatooine
      become: true
      tags:
        - hdp
