- hosts: all
  become: true

  tasks:
    - name: Start Cloudera Manager Agents
      service:
        name: cloudera-scm-agent
        state: restarted

#- hosts: manager
#  become: true
#
#  tasks:
#    - name: Start Cloudera Manager Service
#      service:
#        name: cloudera-scm-server
#        state: restarted