# Based on: https://docs.cloudera.com/cdp-private-cloud/latest/upgrade-cdh/topics/ug_cm_upgrade_server.html
#- import_playbook: ../../devops/db_backup.yaml

## Create / Update CM Repo
- hosts: repo
  become: true

  vars:
    #https://archive.cloudera.com/p/cm7/7.7.1/redhat7/yum
    cm_remote_repo: '{{ cm_remote_repo }}'
    remote_repo_username: '{{ remote_repo_username }}'
    remote_repo_password: '{{ remote_repo_password }}'
    cm_version: 7.7.1
    cm_os: redhat7

  tasks:
    - name: Sync Repo

- hosts: all
  become: true

  vars:
    cm_repo: http://repo.streever.local/repo/cm7/7.7.1/

  tasks:
    - name: Remove CM Repos
      yum_repository:
        name: cloudera-manager
        state: absent

    - name: Add New CM Repos
      yum_repository:
        name: cloudera-manager
        description: Cloudera Manager
        baseurl: '{{ cm_repo }}'
        gpgcheck: no

    - name: Stop the Cloudera Manager Agents
      service:
        name: cloudera-scm-agent
        state: stopped

- hosts: manager
  become: true

  tasks:
    - name: Stop Cloudera Manager
      service:
        name: cloudera-scm-server
        state: stopped
    - name: Upgrade Cloudera Manager
      yum:
        name: cloudera-manager-server,cloudera-manager-daemons
        state: latest
    - name: Start Cloudera Manager
      service:
        name: cloudera-scm-server
        state: started

- hosts: all
  become: true

  tasks:
    - name: Upgrade Cloudera Manager Agents
      yum:
        name: cloudera-manager-agent,cloudera-manager-daemons
        state: latest
    - name: Start Cloudera Manager Agents
      service:
        name: cloudera-scm-agent
        state: started



