# Based on: https://docs.cloudera.com/cdp-private-cloud/latest/upgrade-cdh/topics/ug_cm_upgrade_server.html
#- import_playbook: ../../devops/db_backup.yaml

- hosts: all
  become: true

  tasks:
    - name: Remove CM Repos
      yum_repository:
        name: cloudera-manager
        state: absent
      tags:
        - repo

#    - name: Add CM Repo from Cloudera Repo File
#      get_url:
#        url: '{{ cm_remote_repo_file }}'
#        dest: /etc/yum.repos.d/cloudera-manager.repo
#        url_username: '{{ remote_repo_username }}'
#        url_password: '{{ remote_repo_password }}'
#      tags:
#        - repo

    - name: Add New CM Repos
      yum_repository:
        name: cloudera-manager
        description: "Cloudera Manager {{ cm_version }}"
        baseurl: '{{ cm_remote_repo }}'
        gpgcheck: no
#        gpgkey: '{{ cm_remote_repo }}/RPM-GPG-KEY-cloudera'
        username: '{{ remote_repo_username }}'
        password: '{{ remote_repo_password }}'
      tags:
        - repo

    - name: Stop the Cloudera Manager Agents
      service:
        name: cloudera-scm-agent
        state: stopped

- hosts: manager
  become: true

  tasks:
    - name: Stop Cloudera Manager
      service:
        name: cloudera-scm-server
        state: stopped
      tags:
        - server
    - name: Upgrade Cloudera Manager
      yum:
        name: cloudera-manager-server,cloudera-manager-agent,cloudera-manager-server-db-2
        state: latest
      tags:
        - server
    - name: Start Cloudera Manager
      service:
        name: cloudera-scm-server
        state: started
      tags:
        - server

- hosts: all
  become: true

  tasks:
    - name: Upgrade Cloudera Manager Agents
      yum:
        name: cloudera-manager-agent
#        name: cloudera-manager-agent,cloudera-manager-daemons
        state: latest
      tags:
        - agent
    - name: Start Cloudera Manager Agents
      service:
        name: cloudera-scm-agent
        state: started
      tags:
        - agent



